EXAMPLES_INCLUDE = '*.as' '*.bck' '*.js' '*.json' '*.mx' '*.out' '*.py' '*.sh' '*.txt' '*.yml'
JAVASCRIPT = $(wildcard src/*/*.js) $(wildcard src/*/x-*/*.js)

## ---: -------------------------------------

## standard: run checks on code formatting
standard:
	@npx standard ${JAVASCRIPT}

# These PDFs are generated by hand, so prevent SVG conversion.
docs/doc-generator/fill-in-headers.pdf: src/doc-generator/fill-in-headers.pdf
	cp $< $@
docs/doc-generator/process-plain.pdf: src/doc-generator/process-plain.pdf
	cp $< $@
docs/page-templates/output-conditional.pdf: src/page-templates/output-conditional.pdf
	cp $< $@
docs/page-templates/output-multiple-variables.pdf: src/page-templates/output-multiple-variables.pdf
	cp $< $@
docs/page-templates/output-loop.pdf: src/page-templates/output-loop.pdf
	cp $< $@
docs/page-templates/output-single-variable.pdf: src/page-templates/output-single-variable.pdf
	cp $< $@
docs/page-templates/output-single-constant.pdf: src/page-templates/output-single-constant.pdf
	cp $< $@
docs/page-templates/output-static-text.pdf: src/page-templates/output-static-text.pdf
	cp $< $@
