JAVASCRIPT = $(wildcard src/*/*.js) $(wildcard src/*/x-*/*.js)

## standard: run checks on code formatting
standard:
	@npx standard ${JAVASCRIPT}

# ----------------------------------------------------------------------

# These two PDFs are generated by hand, so don't try to convert SVG.
docs/doc-generator/fill-in-headers.pdf: src/doc-generator/fill-in-headers.pdf
	cp $< $@
docs/doc-generator/process-plain.pdf: src/doc-generator/process-plain.pdf
	cp $< $@
