TARGETS=\
  check-name-lengths.out \
  generator-count.out \
  generator-example.out \
  generator-tree-for.out \
  generator-tree-while.out \
  parse-single-const.out \
  parse-const-func.out \
  walk-ast.out \
  walker-class.out

include ../_rules.mk
