TARGETS=\
  check-name-lengths.txt \
  generator-count.txt \
  generator-example.txt \
  generator-tree-for.txt \
  generator-tree-while.txt \
  parse-single-const.txt \
  parse-const-func.txt \
  walk-ast.txt \
  walker-class.txt

include ../_rules.mk
