TARGETS=\
  check-name-lengths.text \
  generator-count.text \
  generator-example.text \
  generator-tree-for.text \
  generator-tree-while.text \
  parse-single-const.text \
  parse-const-func-and-call.text \
  walk-ast.text \
  walker-class.text

include ../rules.mk

parse-const-func-and-call.text: parse-const-func-and-call.sh parse-const-func-and-call.js
	bash $<
