TARGETS=\
  regex-beginning/regex-complete.txt \
  regex-initial/regex-complete.txt \
  simple-regex.txt \
  simple-selectors-test.txt

include ../rules.mk

simple-selectors-test.txt: simple-selectors.js
