TARGETS=\
  regex-beginning.txt \
  regex-initial.txt \
  regex-recursive.txt \
  simple-regex.txt \
  simple-selectors-test.txt

include ../_rules.mk

regex-beginning.txt: $(wildcard regex-beginning/*.js)
regex-initial.txt: $(wildcard regex-initial/*.js)
regex-recursive.txt: $(wildcard regex-recursive/*.js)
simple-selectors-test.txt: simple-selectors.js
