TARGETS=\
  table-performance-100-03-03.txt \
  table-performance-10000-30-03.txt \
  table-performance-10000-30-10.txt

include ../_rules.mk

table-performance-100-03-03.txt: table-performance.js
table-performance-10000-30-03.txt: table-performance.js
table-performance-10000-30-10.txt: table-performance.js

table-performance.js: build.js
