TARGETS=\
  parser-test.out \
  tokenizer-collapse-example.out \
  tokenizer-test.out

include ../examples.mk

parser-test.out: parser.js tokenizer.js
tokenizer-collapse-example.js: tokenizer-collapse.js
tokenizer-test.out: tokenizer.js
