TARGETS=\
  test-easy-mode.out \
  test-placed.out \
  test-render.out \
  test-wrapped.out

include ../examples.mk

test-easy-mode.out: test/test-easy-mode.js easy-mode.js
test-placed.out: test/test-placed.js placed.js
test-render.out: test/test-render.js placed.js render.js
test-wrapped.out: test/test-wrapped.js wrapped.js
