TARGETS=\
  test-easy-mode.txt \
  test-placed.txt

include ../_rules.mk

test-easy-mode.txt: test/test-easy-mode.js easy-mode.js
test-placed.txt: test/test-placed.js placed-block.js placed-row.js placed-column.js
