TARGETS=\
  always-send-success.out \
  breaking-sandbox.out \
  http-response-parse.out \
  http-response-success.out \
  run-simple-socket.out \
  test-base-http-server.out \
  test-http-file-server.out \
  test-http-json-server.out \
  test-http-params-server.out \
  test-http-response-success.out

include ../examples.mk
