TARGETS=\
  add-timestamps.txt \
  display-only.txt \
  pattern-user-attempt.txt \
  pattern-user-read.txt \
  pattern-user-run.txt \
  update-on-timestamp.txt \
  variable-expander.txt

include ../rules.mk
