TARGETS=\
  hash-file.txt \
  hash-stream.txt \
  hash-text.txt \
  run-hash-existing-async.txt \
  run-hash-existing-promise.txt \
  test-backup.txt \
  tree-test.txt

#  test-check-filesystem.txt FIXME

include ../_rules.mk
