TARGETS=\
  hash-file.text \
  hash-stream.text \
  hash-text.text \
  run-hash-existing-async.text \
  run-hash-existing-promise.text \
  test-backup.text \
  tree-test.text

#  test-check-filesystem.text \

include ../rules.mk
