TARGETS=\
  regex-beginning.out \
  regex-initial.out \
  regex-recursive.out \
  simple-regex.out \
  simple-selectors-test.out

include ../examples.mk

regex-beginning.out: $(wildcard regex-beginning/*.js)
regex-initial.out: $(wildcard regex-initial/*.js)
regex-recursive.out: $(wildcard regex-recursive/*.js)
simple-selectors-test.out: simple-selectors.js
