TARGETS=\
  assign-immediately.out \
  await-fs.out \
  callbacks-with-timeouts.out \
  callbacks-with-zero-timeouts.out \
  count-lines-globbed-files.slice.out \
  count-lines-single-file.out \
  count-lines-with-stat.slice.out \
  count-lines-with-stat-async.slice.out \
  non-blocking.out \
  not-callbacks-alone.out \
  promise-example.out \
  return-await.out \
  return-immediately.out \
  set-immediate.out \
  use-pledge-chained.out \
  use-pledge-motivation.out \
  use-pledge-reject.out \
  use-pledge-return.out \
  use-promise-chained.out

include ../_rules.mk
