TARGETS=\
  assign-immediately.txt \
  callbacks-with-timeouts.txt \
  callbacks-with-zero-timeouts.txt \
  count-lines-globbed-files.txt \
  count-lines-single-file.txt \
  count-lines-with-stat.txt \
  count-lines-with-stat-async.txt \
  non-blocking.txt \
  not-callbacks-alone.txt \
  promise-example.txt \
  return-await.txt \
  return-immediately.txt \
  set-immediate.txt \
  use-pledge-chained.txt \
  use-pledge-motivation.txt \
  use-pledge-reject.txt \
  use-pledge-return.txt \
  use-promise-chained.txt

include ../_rules.mk
