TARGETS=\
  callbacks-with-timeouts.text \
  callbacks-with-zero-timeouts.text \
  count-lines-globbed-files.text \
  count-lines-histogram.text \
  count-lines-single-file.text \
  count-lines-with-stat.text \
  non-blocking.text \
  not-callbacks-alone.text \
  promise-example.text \
  set-immediate.text \
  use-pledge-chained.text \
  use-pledge-motivation.text \
  use-pledge-reject.text \
  use-pledge-return.text \
  use-promise-chained.text

include ../rules.mk
