TARGETS=\
  js-command-line.out \
  js-interactive.out \
  py-command-line.out \
  py-interactive.out

include ../../_rules.mk

js-command-line.out: $(wildcard *.js)
js-interactive.out: $(wildcard *.js)
py-command-line.out: $(wildcard *.py)
py-interactive.out: $(wildcard *.py)
